spring:
  application:
    name: linkup
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3308/linkup}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 1382005a
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    host: localhost
    port: 6380
server:
  post: 8080
  address: 0.0.0.0
  servlet:
    context-path: /
jwt:
  signerKey: "Rc8al3ynqFVftBEV36zVbQAFhOX10h3HkrKGVmAnOipKtNIExStX4jcmligLAcNG"
  valid-duration: 36000 # in seconds
  refreshable-duration: 36000
cloudinary:
  cloud-name: "dcvrdyzo1"
  api-key: ${API_KEY}
  api-secret: ${API_SECRET}